### PR TITLE
Fixed issue with Array3d(3) lookup into texture (Issue #622)

### PR DESCRIPTION
**Pull request by callumhay**
Fix for issue [#622](https://github.com/gpujs/gpu.js/issues/622).

### CODE REVIEW

**Comment by robertleeplummerjr** [comment]
Also, nice work!

**Comment by robertleeplummerjr** [comment]
ping

**Comment by callumhay** [comment]
Hey Robert – sorry for ghosting on this, had totally forgotten about it up until the ping. I threw together a simple unit test (I think I did it right, it appears to work on my local build-tests). Hope it's ok!
-c

**Comment by robertleeplummerjr** [comment]
Hum.  The force push concerns me.

**Comment by callumhay** [comment]
Did I do something wrong? I was just trying to get my fork up to date to start poking around, it's my first time taking a look at the code base for a while and wanted to get my fork up to date. Not sure if this was the right way to do it not... let me know.

**Pull request closed without merging**
