### PR TITLE
261 - webgl2

### PR DESCRIPTION
**Pull request by robertleeplummerjr**
All tests passing, webgl2 iminent.

### CODE REVIEW

**Comment by ubernaut** [comment]
Will the addition of webgl2 support bring in any new features?

**Comment by robertleeplummerjr** [comment]
It'll open the door for the following to be either fixed, or resolved completely:

https://github.com/gpujs/gpu.js/issues/247
https://github.com/gpujs/gpu.js/issues/202
https://github.com/gpujs/gpu.js/issues/166
https://github.com/gpujs/gpu.js/issues/92
https://github.com/gpujs/gpu.js/issues/194

**Comment by robertleeplummerjr** [comment]
All tests that can be are run on `cpu`, `auto`, `gpu`, and then specifically for `webgl` & `webgl2`


Firefox: screen shot 2018-03-08 at 8 03 39 pm

Chrome: 
screen shot 2018-03-08 at 8 05 25 pm

**Comment by robertleeplummerjr** [comment]
Here is a profile of a neural network (brain.js) learning xor, using webgl 2 via gpu.js:
screen shot 2018-03-08 at 8 10 06 pm

**Comment by Blancduman** [comment]
I noticed in gpu.js-2.0.0-rc.13 release you have folder webgl2.. How to use it?

**Comment by robertleeplummerjr** [comment]
If you simply use
```js
const gpu = new GPU();
const kernel = gpu.createKernel(function() {
  // some maths here
  return value;
}, { output: [50] });
```

If it is available on your system, WebGL2 will be used automatically.  If it is not, WebGL1 will be used.  If that isn't available, your CPU will be used.  Likewise in Node, if you do the same, HeadlessGL will be used, and if it is not available, CPU will be used.

**Comment by Blancduman** [comment]
well... I get this error:
```
C:\GitProjects\WebProjects\fighting-gold\backend\node_modules\gpu.js\src\backend\web-gl\kernel.js:406
                        throw new Error('Error compiling fragment shader: ' + gl.getShaderInfoLog(fragShader));
                        ^

Error: Error compiling fragment shader: ERROR: 0:202: '<<=' : bit-wise operator supported in GLSL ES 3.00 only
ERROR: 0:202: 'assign' :  cannot convert from 'const float' to 'highp float'
ERROR: 0:204: '^' : bit-wise operator supported in GLSL ES 3.00 only
ERROR: 0:204: '^' :  wrong operand types  no operation '^' exists that takes a left-hand operand of type 'highp float' and a right operand of type 'const float' (or there is no acceptable conversion)
ERROR: 0:204: '&' : bit-wise operator supported in GLSL ES 3.00 only
ERROR: 0:204: '&' :  wrong operand types  no operation '&' exists that takes a left-hand operand of type 'highp float' and a right operand of type 'const float' (or there is no acceptable conversion)
ERROR: 0:206: '<<' : bit-wise operator supported in GLSL ES 3.00 only
ERROR: 0:206: '<<' :  wrong operand types  no operation '<<' exists that takes a left-hand operand of type 'highp float' and a right operand of type 'const float' (or there is no acceptable conversion)
```

**Pull request merged**
